### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by Drmohammad11** [DJPlaya/Kigen-AC-Redux#13]
L 12/17/2018 - 06:08:17: [SM] Exception reported: Array index out-of-bounds (index -1, limit 4096)
L 12/17/2018 - 06:08:17: [SM] Blaming: kigen-ac_redux.smx
L 12/17/2018 - 06:08:17: [SM] Call stack trace:
L 12/17/2018 - 06:08:17: [SM]   [1] Line 262, kigenac/eyetest.sp::Eyetest_Drop
L 12/17/2018 - 06:08:17: [SM] Exception reported: Stack leak detected: sp:175492 should be 175512!

**Comment by DJPlaya** [comment]
Should be fixed in Commit 8747796
Needs to be verified

**Comment by DJPlaya** [comment]
Verified
