### ISSUE TITLE
Can you update plugin compile with SM 1.10?

### ISSUE THREAD

**Issue by ByKyTa** [DJPlaya/Kigen-AC-Redux#16]
I want compile with SM 1.10.  I hope you will update it

SM 1.10\include\smlib/entities.inc(1773) : fatal error 196: deprecated syntax; see https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Typedefs

**Comment by DJPlaya** [comment]
They dident managed to update it yet > https://github.com/bcserv/smlib/issues/30
So i did.
Ive set the Project target to SM 1.10 - Test it out
