### ISSUE TITLE
I am having error kigen-ac_redux.smx: Unable to load plugin (no debug string table)

### ISSUE THREAD

**Issue by Aprazor** [DJPlaya/Kigen-AC-Redux#18]
kigen-ac_redux.smx: Unable to load plugin (no debug string table)
I am having this issue as because I have the latest version of sourcemod 1.9 and plugin is on 1.8 can you please update it thanks

**Comment by Aprazor** [comment]
kigen-ac_redux.smx: Unable to load plugin (no debug string table)
I am having this issue as because I have the latest version of sourcemod 1.9 and plugin is on 1.8 can you please update it thanks

**Comment by DJPlaya** [comment]
My bad, i was an Idiot thinking SM 1.10 would be backwards compactible to 1.8/1.9

**Comment by DJPlaya** [comment]
From now on KACR will be build with 1.10 with a secondary legacy build for 1.8
