### ISSUE TITLE
Can you please make tutorial on how to install it on sourcemo 1.9

### ISSUE THREAD

**Issue by Aprazor** [DJPlaya/Kigen-AC-Redux#19]
**Describe the Feature you'd like to be added**
A clear and concise Description of what you want

**Describe Alternatives you've considered**
A clear and concise Description of any alternative Solutions or Features you have heard of

**Additional context**
Add any other Context or Media about the Feature Request here

**Comment by Aprazor** [comment]
Can someone help me with this

**Comment by DJPlaya** [comment]
Remove kigen-ac_redux.smx from addons/sourcemod/plugins if you have installed it.
Download and Move kigen-ac_redux_legacy.smx into your addons/sourcemod/plugins Folder.
