### ISSUE TITLE
thank you for update this AntiCheat :X

### ISSUE THREAD

**Issue by Drmohammad11** [DJPlaya/Kigen-AC-Redux#2]
hi my friend!
thabk you for update.

**Comment by DJPlaya** [comment]
Thanks for thanking me, please Spam me when there Problems. ;-)
You should also watch this Project on GitHub, since this AC dosent have an Updater yet
![watcher_picker](https://user-images.githubusercontent.com/24898714/47581240-261fd980-d951-11e8-86fd-d8bd8ffeb174.gif)
