### ISSUE TITLE
[BUG] Cvar Cheker!!

### ISSUE THREAD

**Issue by Drmohammad11** [DJPlaya/Kigen-AC-Redux#23]
**Game**
CSGO

**SourceMod Version**
- [ ] 1.8
- [X] 1.9
- [ ] 1.10
Build Number: 6281

**Describe the Bug**
Disconnect: KACR: 'cl_particle_show_bbox' Violation (bad Query Result)..

**To Reproduce**
Steps to reproduce the Behavior:
1. i used kacr_cvars_enable "1"

**kacr_status output**
kick players after 5 minute

**Additional**
please check !!

**Comment by DJPlaya** [comment]
Thanks for reporting, ime already tracking down this Issue
Ref > #15

**Comment by Nerus87** [comment]
Still the same problem, all players kicked from Server with message example:

> Dropped VENOM from server: KACR: 'cl_particle_show_bbox' Violation (bad Query Result).

`Bad CVar Query Result: 'VENOM <151><STEAM_1:0:XXXXXX><>'<89.XX.XX.XX> returned Query Result "Not found" (expected Okay) on ConVar "cl_particle_show_bbox" (Value "").`

**Comment by DJPlaya** [comment]
Thanks, that Log Snipped really helps me, i will push a Fix in short Time
btw, Ref > #15
