### ISSUE TITLE
Replace SB Plugin File Checks with Library Checks

### ISSUE THREAD

**Issue by DJPlaya** [DJPlaya/Kigen-AC-Redux#33]
Currently we do check if the Sourcebans smx File do exist, but both do register as Library, so we should use these Functions instead.

|-Librarys
"sourcebans"
"sourcebans++"

|-Functions/Events
LibraryExists("###")
public void OnLibraryAdded(const char[] cName)
public void OnLibraryRemoved(const char[] cName)

**Comment by Nerus87** [comment]
Do you use SM Lib (files included with KAC-R) from "https://github.com/bcserv/smlib"?

**Comment by DJPlaya** [comment]
I do use a slightly customized Version of SM Lib 0.9.7, it can be found under "include/smlib_kacr.inc"
