### ISSUE TITLE
All Commands do stop working

### ISSUE THREAD

**Issue by Nerus87** [DJPlaya/Kigen-AC-Redux#34]
**Game**
CSGO
CSS

**SourceMod Version**
- [X ] 1.10
Build Number: [e.g. 6458]

**Describe the Bug**
All commands do stop working once KACR is loaded.
This also occurs with all Modules deactivated

**To Reproduce**
Steps to reproduce the Behavior:
1. Compile plugin
2. Add to the plugins folder
3. Start SRCDS
4. Try to execute the basic command

**Comment by DJPlaya** [comment]
Ime unsure if i did understand that correctly.
So you do start SRCDS with KACR, and it fails to load the Server?

**Comment by Nerus87** [comment]
The server will not load correctly - to the end of loading (loading state will never be finished).
In this case, when you will type any basic SRCDS console command, this command will be not executed and will not trigger any result on the console. The plugin will halt the loading of SRCDS.

**Comment by DJPlaya** [comment]
Ive done some Tests with a basic Setup. It seems that all Commands do stop working, Cvars are completely fine and the Server does run without Problems.
This also occurs when all Modules are deactivated, this makes me wonder whats the Source of this.
I'll follow that up.

**Comment by DJPlaya** [comment]
I dunno why a regular Command Listener is also triggered by Commands in the Console, but it should be fixed now

**Comment by Nerus87** [comment]
Still, the same problem, all plugins did not load correctly when KAC-R working, after unloading KAC-R some of those plugins continue loading and started correctly. After disabling KAC-R all comes to normal.

**Comment by DJPlaya** [comment]
Are you sure you are using the latest Version of KACR?
The Fix i deployed worked fine on my Setup:
-Latest Source- and Metamod
-Win 10 64
-All default SM Plugins
-Latest Server but without Token
-All KACR Modules active
![Picture](https://i.imgur.com/bIaXTqw.png)
#
Since KACR dosent have a Versioning yet, check the File Size, it should be exactly 83.307 Bytes
If you continue having the same Issue even with the latest Version, i need more Information from your Site and we may need to debug this

**Comment by Nerus87** [comment]
I've used last committed version in this time, so this was newest, and I've upgraded SM to last stable version so I've tested on SourceMod Version: 1.10.0.6459

-Latest Source- and Metamod
-Linux x64
-Default SM Plugins + my plugins some other plugins
-Latest Server but with Token
-All KACR Modules active

The latest version (unknown) of KAC-R works perfectly.

I'll try last committed.

**Comment by DJPlaya** [comment]
Commit 6ddc9afd1632c4d39d2cd17e1bf6bf538db0c155 is the one that fixed the Problem for me.

In the newest Commit 8bf6fca6777346c38ce359005da4cfa5ce159808 i did fixed a smaller Bug with the ConVar, please set "kacr_cmds_enable" to 0 in the Config and try again.
If this dosent fix the Bug, i may need to setup an test Environment. What is your Linux Distribution?

**Comment by Nerus87** [comment]
Working properly on both CSS and CSGO on Ubuntu 18.04.3 LTS".

**Comment by DJPlaya** [comment]
Wait, is it completely fixed for you now or did you just disabled "kacr_cmds_enable"?

**Comment by Nerus87** [comment]
>  is it completely fixed, kacr_cmds_enable = 1;
