### ISSUE TITLE
Array index out-of-bounds

### ISSUE THREAD

**Issue by suspectykt** [DJPlaya/Kigen-AC-Redux#37]
**Game**
[CSGO]

**SourceMod Version**
- [ ] 1.8
- [ ] 1.9
- [X] 1.10

Build Number: [6474 - stable]

**Describe the Bug**
Exception reported: Array index out-of-bounds (index -1, limit 2048)
L 03/02/2020 - 14:43:20: [SM] Blaming: kigen-ac_redux.smx
L 03/02/2020 - 14:43:20: [SM] Call stack trace:
L 03/02/2020 - 14:43:20: [SM]   [1] Line 273, kigen-ac_redux/eyetest.sp::Eyetest_Drop
L 03/02/2020 - 14:44:48: [SM] Exception reported: Array index out-of-bounds (index -1, limit 2048)
L 03/02/2020 - 14:44:48: [SM] Blaming: kigen-ac_redux.smx
L 03/02/2020 - 14:44:48: [SM] Call stack trace:
L 03/02/2020 - 14:44:48: [SM]   [1] Line 273, kigen-ac_redux/eyetest.sp::Eyetest_Drop

**To Reproduce**
Steps to reproduce the Behavior:
1. Go to 'Install plugin to server'
2. Click on 'Start Server'
3. Scroll down to 'Check Error log'
4. See Error

**kacr_status output**
[Kigen-AC_Redux] Kigen's Anti-Cheat Redux Status Report
Client Module: On
Client Anti-Rejoin: On
Client Name Protection: On
Command Protection: On
Command Spam Protection: On
CVars Detection: On
Eye Test: On
Anti-Wallhack: On
RCON Crash Prevention: Off

**Comment by DJPlaya** [comment]
Thanks for reporting,
due to a Problem with my Setup, fixing this could take a little longer then usual, thanks for your Patience.

**Comment by DJPlaya** [comment]
Reference #13 
Are you sure that you are using the latest Version?
From what ive seen, i cant imagine why you should receive this Problem.

**Comment by DJPlaya** [comment]
Should be fixed now
