### ISSUE TITLE
kacr_eyes_antiwall crash CSGO SRCDS

### ISSUE THREAD

**Issue by Nerus87** [DJPlaya/Kigen-AC-Redux#40]
**Game**
CSGO

**Metamod Source Version**
Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/6c8495f
Build ID: 971:6c8495f
Loaded As: Valve Server Plugin
Compiled on: Sep  2 2019
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/

**SourceMod Version**
SourceMod Version: 1.10.0.6482
SourcePawn Engine: 1.10.0.6482, jit-x86 (build 1.10.0.6482)
SourcePawn API: v1 = 5, v2 = 12
Compiled on: Apr  9 2020 15:04:10
Built from: https://github.com/alliedmodders/sourcemod/commit/0ac78758
Build ID: 6482:0ac78758
http://www.sourcemod.net/

**KACR build**
https://github.com/DJPlaya/Kigen-AC-Redux/commit/cb1bd15173abdad8c043917b209abac7def148cd

**Describe the Bug**
Server crash (tested on windows only) after the player select team (team menu).
The crash occurred when `kacr_eyes_antiwall` is **enabled**.

**To Reproduce**
Steps to reproduce the Behavior:
1. Compile plugin
2. Run SRCDS
3. Join team
4. See Error

**kacr_status output**
L 04/19/2020 - 20:47:43: 'Nerus<3><STEAM_1:1:XXX><>'<192.168.56.1> used Command: vmodenable 1
L 04/19/2020 - 20:47:43: 'Nerus<3><STEAM_1:1:XXX><>'<192.168.56.1> used Command: vban 0 0
L 04/19/2020 - 20:47:43: 'Nerus<3><STEAM_1:1:XXX><>'<192.168.56.1> used Command: joingame 
L 04/19/2020 - 20:47:46: 'Nerus<3><STEAM_1:1:XXX><>'<192.168.56.1> used Command: jointeam 2 1

**Additional**
*[SM] Exception reported: Stack leak detected: sp:186760 should be 186772!
*SRCDS will create `mdmp` in-game mod folder.

**Comment by DJPlaya** [comment]
Thanks for reporting.

Ime pretty wondered about this Issue since i do have Test Networks that run CSGO.
Could you please link me the Crash for further Analysis?

**Comment by Nerus87** [comment]
Sure: [srcds_20200422_174728_1_x2340EB38_accessviolation.zip](https://github.com/DJPlaya/Kigen-AC-Redux/files/4517242/srcds_20200422_174728_1_x2340EB38_accessviolation.zip)

**Comment by DJPlaya** [comment]
> Sure: [srcds_20200422_174728_1_x2340EB38_accessviolation.zip](https://github.com/DJPlaya/Kigen-AC-Redux/files/4517242/srcds_20200422_174728_1_x2340EB38_accessviolation.zip)

Hey, sorry for the late Reply.
I cant read much out of this Crash, but from what i see it should be related to sdkhooks so it definitly is related to the Eyecheck. What i am wondered about is that is works fine on my test Setup, i need to further debug this.
Can you maybe provide the Crash on Accelerator? Its a lot easyer for me, if that s not possible, please use the -debug launch option.

**Comment by DJPlaya** [comment]
This Issue will be marked as solved in short Time if no other Information can be provided
