### ISSUE TITLE
[Crash] Server crashes after player join

### ISSUE THREAD

**Issue by Nerus87** [DJPlaya/Kigen-AC-Redux#51]
**Game**
CSGO

**MetaMod: Source Version**
version 1.11.0-dev+1144

**SourceMod Version**
- [ ] 1.8
- [ ] 1.9
- [X] 1.10
Build Number: 1.10.0.6502, jit-x86 (build 1.10.0.6502)

**Platform**
- Local PC
- Windows 10 x64 (updated)
- SRCDS

**Sourcemod extensions**
[SM] Displaying 7 extensions:
[01] Automatic Updater (1.10.0.6502): Updates SourceMod gamedata files
[02] Webternet (1.10.0.6502): Extension for interacting with URLs
[03] Accelerator (2.5.0): SRCDS Crash Handler
[04] CS Tools (1.10.0.6502): CS extended functionality
[05] BinTools (1.10.0.6502): Low-level C/C++ Calling API
[06] SDK Tools (1.10.0.6502): Source SDK Tools
[07] SDK Hooks (1.10.0.6502): Source SDK Hooks

**Accelerator crash report**
[CRASH] Accelerator uploaded crash dump: Crash ID: LDZL-MJUV-4JMV
Got a presubmit token from server: 52c35ae8d95e7f30c578dd327757eba8
Uploaded crash dump: Crash ID: LDZL-MJUV-4JMV

**Describe the Bug**
The server crashes after a player joins the game.

**To Reproduce**
Steps to reproduce the Behavior:
1. Download server files
2. Remove all of the plugins
3. Compile plugin
4. Join the server

**Additional**
- Config attached,
- On CSS works fine.

[Kigen-AC_Redux.txt](https://github.com/DJPlaya/Kigen-AC-Redux/files/5801772/Kigen-AC_Redux.txt)
[srcds_20210112_122203_1_x1A8AEAF8_breakpoint.zip](https://github.com/DJPlaya/Kigen-AC-Redux/files/5801775/srcds_20210112_122203_1_x1A8AEAF8_breakpoint.zip)

**Comment by Nerus87** [comment]
I forgot to enable logging on a debug.
Attached logs.

[KACR_CmdLog_0.log](https://github.com/DJPlaya/Kigen-AC-Redux/files/5801826/KACR_CmdLog_0.log)
[KACR_CmdLog_1.log](https://github.com/DJPlaya/Kigen-AC-Redux/files/5801881/KACR_CmdLog_1.log)
[errors_20210112.log](https://github.com/DJPlaya/Kigen-AC-Redux/files/5801827/errors_20210112.log)

Additional, I have weird behavior of spam connect functionality.
When I'm trying to join the game from the browser in-game, I've got the ban for rejoining.

`L 01/12/2021 - 12:13:47: [kigen-ac_redux.smx] 'Nerus<2><STEAM_1:1:20087879><>'<10.0.0.8> was banned for 1 minute for spam connecting
L 01/12/2021 - 12:13:47: 'Nerus<2><STEAM_1:1:20087879><>'<10.0.0.8> was banned for 1 minute for spam connecting
Dropped Nerus from server: Connection rejected by game`

**Comment by DJPlaya** [comment]
Ref. #40
The previous Ticked was closed because of an Timeout, Discussion continues here.

Thanks for reporting!
Strangely, this is the same Bug as last Time you have submitted it. What I have noticed is that you do compile the Plugin yourself, except for this, i cant really imagine a Reason for the Crash since KACR works on multiply Systems.
Can you try the precompiled Version from GitHub? I could imagine that you maybe do have an outdated Include or something similar which is causing this Behavior.

For the Connect Ban, you can just adjust the 'kacr_client_antispamconnect' ConVar. Its Value is the Seconds to prevent someone from reestablishing a Connection, 0 to disable-

**Comment by Nerus87** [comment]
Nope, same situation, server crash on player join the game.
I've copy and paste this version of the plugin from the master branch.
![obraz](https://user-images.githubusercontent.com/3099926/104353445-2f80c680-5508-11eb-8d27-bdd14aa61f9e.png)
![obraz](https://user-images.githubusercontent.com/3099926/104353801-9a320200-5508-11eb-8084-9181bbab2657.png)

**Comment by Nerus87** [comment]
If you want to we can do a meeting on the discord  - I'll share my screen with you, to show what I am doing one by one? Maybe this will tell you something.

**Comment by DJPlaya** [comment]
Sorry for the long Delay. The last Update may have fixed the Issue. I will investigate further once the Beta Update is merged.

**Comment by Nerus87** [comment]
Ok, I'll look at this update and check it on my servers.

**Comment by Nerus87** [comment]
Tell me please, where is your last commit that fixing the problem, what I see now it is only `1804ccb` from `27 Jul 2020`

**Comment by DJPlaya** [comment]
I have only pushed the change to the Beta Branch so far which isent that stable. Ill merge the whole Branch soon when its better tested.

Edit:
The Commit was df6fa93
