### ISSUE TITLE
Exception reported: Client index 1634036816 is invalid (arg 4)

### ISSUE THREAD

**Issue by panikajo** [DJPlaya/Kigen-AC-Redux#52]
**Game**
[e.g. CSGO]

**SourceMod Version**
- [ ] 1.10

L 01/31/2021 - 09:44:12: [SM] Blaming: kigen-ac_redux.smx
L 01/31/2021 - 09:44:12: [SM] Call stack trace:
L 01/31/2021 - 09:44:12: [SM]   [0] VFormat
L 01/31/2021 - 09:44:12: [SM]   [1] Line 313, kigen-ac_redux/stocks.sp::KACR_Action
L 01/31/2021 - 09:44:12: [SM]   [2] Line 249, kigen-ac_redux/client.sp::Client_OnClientConnect
L 01/31/2021 - 09:44:12: [SM]   [3] Line 417, kigen-ac_redux.sp::OnClientConnect

**Comment by DJPlaya** [comment]
Couldent reproduce this Error. Its propably got fixed a while ago since its from the Beta Branch
